#!/usr/bin/env bash
#
# One-time setup: create the GitHub repo, wire up Pages, push, deploy.
#
#   ./setup-github-pages.sh                 # interactive
#   ./setup-github-pages.sh myrepo public   # non-interactive
#
# Requirements: git, and the GitHub CLI (https://cli.github.com) logged in
# via `gh auth login`.

set -euo pipefail

BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GRN=$'\033[32m'
YLW=$'\033[33m'; RST=$'\033[0m'

say()  { printf '%s▸%s %s\n' "$YLW" "$RST" "$1"; }
ok()   { printf '%s✓%s %s\n' "$GRN" "$RST" "$1"; }
die()  { printf '%s✗%s %s\n' "$RED" "$RST" "$1" >&2; exit 1; }

cd "$(dirname "$0")"

# ── preflight ────────────────────────────────────────────────────────────
command -v git >/dev/null || die "git is not installed."
command -v gh  >/dev/null || die "GitHub CLI not found. Install it: https://cli.github.com"
gh auth status >/dev/null 2>&1 || die "Not logged in. Run: gh auth login"

USER_LOGIN=$(gh api user --jq .login)
ok "Authenticated as ${BOLD}${USER_LOGIN}${RST}"

# ── repo name ────────────────────────────────────────────────────────────
REPO="${1:-}"
if [[ -z "$REPO" ]]; then
  printf '\n'
  printf '  %sRepository name%s\n' "$BOLD" "$RST"
  printf '  %s· "%s.github.io"  → site lives at https://%s.github.io%s\n' \
    "$DIM" "$USER_LOGIN" "$USER_LOGIN" "$RST"
  printf '  %s· anything else   → site lives at https://%s.github.io/<name>%s\n\n' \
    "$DIM" "$USER_LOGIN" "$RST"
  read -rp "  Name [${USER_LOGIN}.github.io]: " REPO
  REPO="${REPO:-${USER_LOGIN}.github.io}"
fi

VISIBILITY="${2:-public}"
[[ "$VISIBILITY" == "public" || "$VISIBILITY" == "private" ]] \
  || die "Visibility must be 'public' or 'private'."

# Pages on a private repo needs GitHub Pro / Team / Enterprise.
if [[ "$VISIBILITY" == "private" ]]; then
  say "Note: Pages from a private repo requires a paid GitHub plan."
fi

# ── work out site / base ─────────────────────────────────────────────────
if [[ "$REPO" == "${USER_LOGIN}.github.io" ]]; then
  SITE_URL="https://${USER_LOGIN}.github.io"
  BASE_PATH=""
else
  SITE_URL="https://${USER_LOGIN}.github.io"
  BASE_PATH="/${REPO}"
fi
FINAL_URL="${SITE_URL}${BASE_PATH}"

say "Configuring astro.config.mjs for ${BOLD}${FINAL_URL}${RST}"

# Regenerated wholesale rather than patched — a regex over this file would also
# match the example lines inside its own comment block.
if [[ -n "$BASE_PATH" ]]; then
  BASE_LINE="  base: '${BASE_PATH}',"
else
  BASE_LINE="  // base: '/your-repo-name',   // project sites only"
fi

cat > astro.config.mjs <<EOF
// @ts-check
import { defineConfig } from 'astro/config';

// Generated by setup-github-pages.sh for ${FINAL_URL}
//
//   User site    — repo "<username>.github.io" → no \`base\`
//   Project site — any other repo name         → base: '/<repo-name>'
export default defineConfig({
  site: '${SITE_URL}',
${BASE_LINE}
  output: 'static',
  trailingSlash: 'ignore',
  build: {
    // Emit /about/index.html style URLs — friendlier on GitHub Pages.
    format: 'directory',
  },
});
EOF
ok "astro.config.mjs updated"

# ── build once locally so failures surface here, not in CI ───────────────
if [[ ! -d node_modules ]]; then
  say "Installing dependencies…"
  npm install
fi
say "Test build…"
npm run build >/dev/null || die "Build failed. Fix the errors above, then re-run."
ok "Build succeeded"

# ── git ──────────────────────────────────────────────────────────────────
if [[ ! -d .git ]]; then
  git init -q
  git symbolic-ref HEAD refs/heads/main
  ok "Initialised git repo"
fi
git add -A
git diff --cached --quiet || git commit -qm "Initial commit: academic portfolio site"
git branch -M main

# ── create remote (or reuse an existing one) ─────────────────────────────
if gh repo view "${USER_LOGIN}/${REPO}" >/dev/null 2>&1; then
  say "Repo ${USER_LOGIN}/${REPO} already exists — reusing it."
  git remote get-url origin >/dev/null 2>&1 \
    || git remote add origin "https://github.com/${USER_LOGIN}/${REPO}.git"
else
  say "Creating ${USER_LOGIN}/${REPO} (${VISIBILITY})…"
  gh repo create "${REPO}" "--${VISIBILITY}" --source=. --remote=origin
  ok "Repo created"
fi

say "Pushing to main…"
git push -u origin main
ok "Pushed"

# ── enable Pages with the GitHub Actions build type ──────────────────────
say "Enabling GitHub Pages (source: GitHub Actions)…"
if gh api "repos/${USER_LOGIN}/${REPO}/pages" >/dev/null 2>&1; then
  gh api -X PUT "repos/${USER_LOGIN}/${REPO}/pages" \
    -f build_type=workflow >/dev/null && ok "Pages source set to Actions"
else
  gh api -X POST "repos/${USER_LOGIN}/${REPO}/pages" \
    -f build_type=workflow >/dev/null 2>&1 \
    && ok "Pages enabled" \
    || say "Could not enable Pages via API. Turn it on manually: Settings → Pages → Source: GitHub Actions"
fi

# ── done ─────────────────────────────────────────────────────────────────
printf '\n'
ok "Setup complete."
printf '\n'
printf '  %sLive URL%s      %s\n' "$BOLD" "$RST" "$FINAL_URL"
printf '  %sActions%s       https://github.com/%s/%s/actions\n' "$BOLD" "$RST" "$USER_LOGIN" "$REPO"
printf '\n'
printf '  %sThe first deploy takes 1–2 minutes. Watch it with:%s\n' "$DIM" "$RST"
printf '      gh run watch\n'
printf '\n'
printf '  %sFrom here on, every push to main redeploys automatically.%s\n' "$DIM" "$RST"
printf '\n'
